/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TP13;

import java.sql.ResultSet;
import javax.swing.DefaultListModel;

/**
 *
 * @author ASUS
 */
public class UI_Pegawai extends javax.swing.JFrame {

    /**
     * Creates new form UI_Pegawai
     */
    public UI_Pegawai() {
        initComponents();
        cleartext();
        displayData();
        setLocationRelativeTo(null);
    }
    
    public void cleartext() {
        labelValueNama.setText(null);
        labelValuePosisi.setText(null);
        labelValueTglLahir.setText(null);
    }
    
    public void displayData() {
        try {
            DefaultListModel<String> model = new DefaultListModel<>();
            Database db = new Database();
            String sql = "SELECT * FROM pegawai";
            ResultSet result = db.getData(sql);
            while (result.next()) {
                model.addElement(result.getString("nama"));
            }
            listPegawai.setModel(model);
        } catch(Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPegawai = new javax.swing.JList<>();
        labelJudul = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelPosisi = new javax.swing.JLabel();
        labelTglLahir = new javax.swing.JLabel();
        labelValueNama = new javax.swing.JLabel();
        labelValuePosisi = new javax.swing.JLabel();
        labelValueTglLahir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listPegawai);

        labelJudul.setText("Daftar Pegawai");

        labelNama.setText("Nama");

        labelPosisi.setText("Posisi");

        labelTglLahir.setText("Tgl Lahir");

        labelValueNama.setText("nama");

        labelValuePosisi.setText("posisi");

        labelValueTglLahir.setText("tgl_lahir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNama)
                    .addComponent(labelPosisi)
                    .addComponent(labelTglLahir))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJudul)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValueNama)
                            .addComponent(labelValuePosisi)
                            .addComponent(labelValueTglLahir))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(labelNama)
                        .addGap(42, 42, 42)
                        .addComponent(labelPosisi)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTglLahir)
                            .addComponent(labelValueTglLahir))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelJudul)
                .addGap(36, 36, 36)
                .addComponent(labelValueNama)
                .addGap(42, 42, 42)
                .addComponent(labelValuePosisi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPegawaiMouseClicked
        // TODO add your handling code here:
        try {
            String nama = listPegawai.getSelectedValue();
            Database db = new Database();
            String sql = "SELECT * FROM pegawai WHERE nama='" + nama+"'";
            ResultSet result = db.getData(sql);
            while (result.next()) {
                labelValueNama.setText(result.getString("nama"));
                labelValuePosisi.setText(result.getString("posisi"));
                labelValueTglLahir.setText(result.getString("tgl_lahir"));
            }
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_listPegawaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPosisi;
    private javax.swing.JLabel labelTglLahir;
    private javax.swing.JLabel labelValueNama;
    private javax.swing.JLabel labelValuePosisi;
    private javax.swing.JLabel labelValueTglLahir;
    private javax.swing.JList<String> listPegawai;
    // End of variables declaration//GEN-END:variables
}
